Rails.application.config.assets.precompile += %w( snippet-text.png )
Rails.application.config.assets.precompile += %w( snippet-image.png )
Rails.application.config.assets.precompile += %w( snippet-image-text.png )
Rails.application.config.assets.precompile += %w( snippet-text-image.png )
Rails.application.config.assets.precompile += %w( default.jpg )